### ISSUE TITLE
breakfast scene from ddish-gi-paper-scenes.zip looks broken

### ISSUE THREAD

**Issue by tigrazone** [vga-group/tauray#50] opened 2024-10-17 12:08 UTC
I rendered your scene with vk_gltf_renderer and have issue.
take look at [screenshots ](https://github.com/nvpro-samples/vk_gltf_renderer/issues/19) and talk about uvs ant normals and tangents

**Comment by juliusikkala** [comment] 2024-10-21 14:45
Yeah, we've seen these busted tangents happen before with models exported from Blender, which indeed uses MikkTSpace. The discussion in that thread aligns with my experiences, it's exactly caused by having identical UV coordinates for multiple vertices on a triangle. We already have mitigations in place for this in Tauray.

I'm going to be closing this issue since it's not really Tauray-related. Thanks for the heads-up, still!

**Closed by juliusikkala** 2024-10-21 14:45 UTC
